-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "28")

-- Settings
hl.config({
    general = {
        border_size = 4,
        gaps_in = 5,
    },
    input = {
        accel_profile = "flat",
        kb_layout = "fr,us",
        numlock_by_default = false,
        sensitivity = 0.25,
    },
})
