-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        border_size = 4,
    },
    input = {
        accel_profile = "flat",
        kb_layout = "fr,us",
        sensitivity = 0.25,
    },
})

-- Monitors
hl.monitor({
    output = "DP-1",
    disabled = false,
    mode = "1920x1080@144.00Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
